FROM mapasculturais/mapasculturais:v5.0.0-RC

#RUN git clone https://github.com/hacklabr/mapasculturais-multipleLocalAuth /var/www/html/protected/application/plugins/MultipleLocalAuth
#RUN curl https://raw.githubusercontent.com/opauth/facebook/master/FacebookStrategy.php > /var/www/html/protected/application/plugins/MultipleLocalAuth/Facebook/FacebookStrategy.php

#COPY compose/common/config.php /var/www/html/protected/application/conf/config.php
#COPY compose/common/config.d /var/www/html/protected/application/conf/conf-common.d
#COPY compose/production/config.d /var/www/html/protected/application/conf/config.d

#COPY src/protected/application/lib/MapasCulturais/AuthProviders/ /var/www/html/protected/application/lib/MapasCulturais/AuthProviders/
#COPY src/protected/application/themes /var/www/html/protected/application/themes

