openapi: 3.0.2
info:
  title: API Mapas Culturais V2 - OpenAPI 3.0
  description: |-
    Descreva aqui o que a API do Mapas faz

    Links Importantes:
    - [Mapa Cultural do Ceará](https://mapacultural.secult.ce.gov.br/)
    - [API V2](https://mapacultural.secult.ce.gov.br/api/v2)
    - [Github](https://github.com/secultce/mapacultural)
  contact:
    email: contato@email.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.18
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api/v2
tags:
  - name: Agentes
    description: Rotas relacionadas aos agentes
  - name: Espaços
    description: Rotas relacionadas aos espaços
  - name: Eventos
    description: Rotas relacionadas aos eventos
  - name: Oportunidades
    description: Rotas relacionadas às oportunidades
  - name: Projetos
    description: Rotas relacionadas aos projetos
  - name: Selos
    description: Rotas relacionadas aos selos
  - name: Termos
    description: Rotas relacionadas aos termos
paths:
  /agents:
    $ref: './components/paths/agent/group-get-post.yaml'
  /agents/{id}:
    $ref: './components/paths/agent/group-param-id.yaml'
  /agents/{id}/opportunities:
    $ref: './components/paths/agent/get-opportunity.yaml'
  /agents/types:
    $ref: './components/paths/agent/get-type-list.yaml'
  /events:
    $ref: './components/paths/event/group-get-post.yaml'
  /events/{id}:
    $ref: './components/paths/event/group-param-id.yaml'
  /events/types:
    $ref: './components/paths/event/get-type-list.yaml'
  /opportunities:
    $ref: './components/paths/opportunity/group-get-post.yaml'
  /opportunities/{id}:
    $ref: './components/paths/opportunity/group-param-id.yaml'
  /projects:
    $ref: './components/paths/project/group-get-post.yaml'
  /projects/{id}:
    $ref: './components/paths/project/group-param-id.yaml'
  /seals:
    $ref: './components/paths/seal/group-get-post.yaml'
  /seals/{id}:
    $ref: './components/paths/seal/group-param-id.yaml'
  /spaces:
    $ref: './components/paths/space/group-get-post.yaml'
  /spaces/{id}:
    $ref: './components/paths/space/group-param-id.yaml'
  /spaces/{id}/events:
    $ref: './components/paths/space/get-events-by-spaces.yaml'
  /terms:
    $ref: './components/paths/term/group-get-post.yaml'
  /terms/{id}:
    $ref: './components/paths/term/group-param-id.yaml'
components:
  schemas:
    Agent:
      $ref: './components/schemas/agent.yaml'
    Events:
      $ref: './components/schemas/event.yaml'
    EventOccurrence:
      $ref: './components/schemas/event-occurrence.yaml'
    Opportunity:
      $ref: './components/schemas/opportunity.yaml'
    Project:
      $ref: './components/schemas/project.yaml'
    Seal:
      $ref: './components/schemas/seal.yaml'
    Space:
      $ref: './components/schemas/space.yaml'
    Term:
      $ref: './components/schemas/term.yaml'
