services:
  web:
    image: ghcr.io/redemapas/mapas-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - database
    environment:
      CACHE_ASSETS_URL: 'false'
      XDEBUG_MODE: coverage
    ports:
      - 4242:80
    volumes:
      - ./:/app
      - var-files:/app/var/
      - assets-files:/app/public/assets
      - user-public-files:/app/public/files/
      - sessions-files:/app/var/sessions/
      - doctrine-files:/app/var/DoctrineProxies/
    command: php -S 0.0.0.0:80 -q -t /app/public /app/router.php

  tmui-postgres:
    image: achristmascarl/rainfrog:latest

  recreate-pending-pcache:
    image: ghcr.io/redemapas/mapas-php
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  execute-job:
    image: ghcr.io/redemapas/mapas-php
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app

  db-update:
    image: ghcr.io/redemapas/mapas-php
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 80
