<?php
use MapasCulturais\i;

return array(
    1 => array(
       // 'slug' => i::__('tag'),
    'slug' => 'tag',
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        //'slug' => i::__('area'),
'slug' => 'area',
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Antropologia'),
            i::__('Arqueologia'),
            i::__('Arquitetura-Urbanismo'),
            i::__('Arquivo'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Artes Visuais'),
            i::__('Artesanato'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Circo'),
            i::__('Comunicação'),
            i::__('Cultura Cigana'),
            i::__('Cultura Digital'),
            i::__('Cultura Estrangeira (imigrantes)'),
            i::__('Cultura Indígena'),
            i::__('Cultura LGBT'),
            i::__('Cultura Negra'),
            i::__('Cultura Popular'),
            i::__('Dança'),
            i::__('Design'),
            i::__('Direito Autoral'),
            i::__('Economia Criativa'),
            i::__('Educação'),
            i::__('Esporte'),
            i::__('Filosofia'),
            i::__('Fotografia'),
            i::__('Gastronomia'),
            i::__('Gestão Cultural'),
            i::__('História'),
            i::__('Jogos Eletrônicos'),
            i::__('Jornalismo'),
            i::__('Leitura'),
            i::__('Literatura'),
            i::__('Livro'),
            i::__('Meio Ambiente'),
            i::__('Mídias Sociais'),
            i::__('Moda'),
            i::__('Museu'),
            i::__('Música'),
            i::__('Novas Mídias'),
            i::__('Ópera'),
            i::__('Patrimônio Cultural'),
            i::__('Patrimônio Imaterial'),
            i::__('Patrimônio Material'),
            i::__('Pesquisa'),
            i::__('Produção Cultural'),
            i::__('Rádio'),
            i::__('Saúde'),
            i::__('Sociologia'),
            i::__('Teatro'),
            i::__('Televisão'),
            i::__('Turismo'),
           i::__('Outros')
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Artes Integradas'),
            i::__('Artes Visuais'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Cultura Digital'),
            i::__('Cultura Indígena'),
            i::__('Cultura Tradicional'),
            i::__('Curso ou Oficina'),
            i::__('Dança'),
            i::__('Exposição'),
            i::__('Hip Hop'),
            i::__('Livro e Literatura'),
            i::__('Música Popular'),
            i::__('Música Erudita'),
            i::__('Palestra, Debate ou Encontro'),
            i::__('Rádio'),
            i::__('Teatro'),
            i::__('Outros')
        )
    ),
    4 => array(
        'slug' => 'funcao',
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__("Aderecista"),
            i::__("Adestrador(a) para Artes Cênicas"),
            i::__("Afinador de Instrumentos"),
            i::__("Ajudante de Câmera"),
            i::__("Ajudante de Locação"),
            i::__("Ajudante de Objetos"),
            i::__("Ajudante de Produção"),
            i::__("Amestrador(a)"),
            i::__("Aplicador(a) de sign"),
            i::__("Armeiro(a)"),
            i::__("Assessor(a) de Comunicação"),
            i::__("Assistente Administrativo"),
            i::__("Assistente de Arte"),
            i::__("Assistente de Artista Gráfico"),
            i::__("Assistente de Backstage"),
            i::__("Assistente de Camarim"),
            i::__("Assistente de Câmera"),
            i::__("Assistente de Cenotécnica"),
            i::__("Assistente de Continuidade"),
            i::__("Assistente de Controller"),
            i::__("Assistente de Criação Artística"),
            i::__("Assistente de Edição"),
            i::__("Assistente de Edição de Som"),
            i::__("Assistente de Eletricista"),
            i::__("Assistente de Figurino"),
            i::__("Assistente de Ilha de Edição"),
            i::__("Assistente de Maquiagem"),
            i::__("Assistente de Maquinaria"),
            i::__("Assistente de Montagem"),
            i::__("Assistente de Objetos"),
            i::__("Assistente de Pós Produção"),
            i::__("Assistente de Produção (Base ou Set"),
            i::__("Assistente de Produção de Arte"),
            i::__("Assistente de Produção de Elenco"),
            i::__("Assistente de Produção de Locação"),
            i::__("Assistente de Produção em geral"),
            i::__("Assistente de Produção Musical"),
            i::__("Assistente de Roteiro"),
            i::__("Assistente de Som"),
            i::__("Assistente de Transporte"),
            i::__("Assistente Mixador(a)"),
            i::__("Audiodescritor(a)"),
            i::__("Barreira"),
            i::__("Bilheteiro(a)"),
            i::__("Bordadeiro(a)"),
            i::__("Cabeleireiro"),
            i::__("Cabeleireiro(a)"),
            i::__("Camareiro(a)"),
            i::__("Capataz(a) - Montador(a)"),
            i::__("Carpinteiro(a)"),
            i::__("Cenógrafo(a)"),
            i::__("Cenotécnico(a)"),
            i::__("Chefe de Maquinária"),
            i::__("Cinegrafista"),
            i::__("Colorista"),
            i::__("Colorista Assistente"),
            i::__("Consultor de Imagem"),
            i::__("Consultor em Legendagem"),
            i::__("Consultor(a) em Audiodescrição"),
            i::__("Consultor(a) em Braille"),
            i::__("Consultor(a) em Libras"),
            i::__("Continuista"),
            i::__("Contrarregra"),
            i::__("Coolhunter"),
            i::__("Coordenador(a) de Palco"),
            i::__("Cortineiro(a)"),
            i::__("Costureiro(a)"),
            i::__("Design de Montagem"),
            i::__("Diagramador(a)"),
            i::__("Digitalizador(a)"),
            i::__("Diretor(a) de Palco"),
            i::__("Editor de Partituras"),
            i::__("Editor(a)"),
            i::__("Editor(a) de Som"),
            i::__("Eletricista"),
            i::__("Eletricista Chefe"),
            i::__("Engenheiro(a) de Som"),
            i::__("Ensaiador(a)"),
            i::__("Estampador"),
            i::__("Figurinista"),
            i::__("Foley"),
            i::__("Guia-intérprete de língua de sinais"),
            i::__("Iluminador"),
            i::__("Iluminador(a)"),
            i::__("Legendista ou Tradutor(a)"),
            i::__("Logger"),
            i::__("Luthier"),
            i::__("Maquiador"),
            i::__("Maquiador(a)"),
            i::__("Maquinista"),
            i::__("Marcador(a) de Cena"),
            i::__("Mediador(a)"),
            i::__("Mestre(a) de Pista"),
            i::__("Montador(a)"),
            i::__("Montador(a) de Palco"),
            i::__("Motorista de Audiovisual"),
            i::__("Músico-Musicista"),
            i::__("Operador(a) de Luz"),
            i::__("Operador(a) de Som"),
            i::__("Outra função técnica"),
            i::__("Passador (a)"),
            i::__("Peruqueiro"),
            i::__("Peruqueiro(a)"),
            i::__("Pilotista"),
            i::__("Produtor de Casting"),
            i::__("Produtor(a) de Casting/Booker"),
            i::__("Produtor(a) Fonográfico"),
            i::__("Radialista"),
            i::__("Roadie"),
            i::__("Sapateiro"),
            i::__("Secretario(a) de Frente"),
            i::__("Secretário(a) Teatral"),
            i::__("Serigrafista"),
            i::__("Sonoplasta"),
            i::__("Tatuador"),
            i::__("Técnico de Luz"),
            i::__("Técnico(a) Contábil"),
            i::__("Técnico(a) de Estúdio"),
            i::__("Técnico(a) de Luz"),
            i::__("Técnico(a) de Palco"),
            i::__("Técnico(a) de Som"),
            i::__("Técnico(a) de Som Direto"),
            i::__("Tradutor(a) ou Intérprete de Libras"),
            i::__("Transcritor ou Revisor em Braille"),
            i::__("Visagista"),
            i::__("Visual Merchandiser"),
            i::__("Vitrinista"),
        )
    )
);
