<?php
use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Opportunity',
        ),
        'restricted_terms' => array(
            i::__('Acervos'),
            i::__('Acessibilidade Cultural'),
            i::__('Agrofloresta'),
            i::__('Animação'),
            i::__('Antropologia'),
            i::__('Áreas Técnicas'),
            i::__('Arqueologia'),
            i::__('Arquitetura e Urbanismo'),
            i::__('Arquivos'),
            i::__('Arte de Plásticas'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Arte Gráfica'),
            i::__('Arte Santeira'),
            i::__('Artes Circenses'),
            i::__('Artes Visuais'),
            i::__('Artesanato'),
            i::__('Artesanato com Reciclados'),
            i::__('Artesanato em Cerâmica'),
            i::__('Artesanato em Fibra Vegetal'),
            i::__('Artesanato em Fio'),
            i::__('Artesanato em Madeira'),
            i::__('Artesanato em Metal'),
            i::__('Artesanato em Pedra'),
            i::__('Artesanato em Tecido'),
            i::__('Audiolivro'),
            i::__('Audiovisual e Mídias Interativas'),
            i::__('Audiovisual Expandido'),
            i::__('Axé'),
            i::__('Baião'),
            i::__('Baião (dança)'),
            i::__('Ballet'),
            i::__('Banda'),
            i::__('Banda Sinfônica'),
            i::__('Bandas de Congo e Ticumbi'),
            i::__('Biblioteca'),
            i::__('Biblioteca tombada'),
            i::__('Biblioteconomia'),
            i::__('Bioconstrução'),
            i::__('Biografia e Autobiografia'),
            i::__('Bloco de Carnaval'),
            i::__('Boi Bumbá'),
            i::__('Bordado'),
            i::__('Breakdance'),
            i::__('Brega Funk'),
            i::__('Caboclinho'),
            i::__('Caçada da Rainha'),
            i::__('Calypso'),
            i::__('Canto'),
            i::__('Canto Coral'),
            i::__('Capoeira'),
            i::__('Carimbó'),
            i::__('Carimbó (Dança)'),
            i::__('Carnaval'),
            i::__('Cavalhadas'),
            i::__('Cavalo Marinho'),
            i::__('Centro de Memória e patrimônio'),
            i::__('Ciência Política'),
            i::__('Cinema'),
            i::__('Cinemateca'),
            i::__('Ciranda'),
            i::__('Circo'),
            i::__('Circo Contemporâneo'),
            i::__('Circo de Rua'),
            i::__('Circo Itinerante'),
            i::__('Circo Tradicional'),
            i::__('Coco'),
            i::__('Comédia'),
            i::__('Comunicação'),
            i::__('Congada'),
            i::__('Congado'),
            i::__('Contação de histórias'),
            i::__('Conteúdo Audiovisual por Demanda'),
            i::__('Conto'),
            i::__('Cordel'),
            i::__('Criação literária'),
            i::__('Crochê'),
            i::__('Crônica'),
            i::__('Cultivo e extração tradicional'),
            i::__('Cultura Alemã'),
            i::__('Cultura Alimentar'),
            i::__('Cultura Cigana'),
            i::__('Cultura da juventude de povos e comunidades tradicionais'),
            i::__('Cultura das comunidades de fundo e fecho de pasto'),
            i::__('Cultura das comunidades quilombolas'),
            i::__('Cultura das quebradeiras de coco babaçu'),
            i::__('Cultura DEF'),
            i::__('Cultura Digital'),
            i::__('Cultura do Povo Arara'),
            i::__('Cultura do Povo Araweté'),
            i::__('Cultura do Povo Ashaninka'),
            i::__('Cultura do Povo Bororo'),
            i::__('Cultura do Povo Cultura Fulni-ô'),
            i::__('Cultura do Povo Enawenê-Nawê'),
            i::__('Cultura do Povo Gavião'),
            i::__('Cultura do Povo Guarani'),
            i::__('Cultura do Povo Ikpeng'),
            i::__('Cultura do Povo Javari'),
            i::__('Cultura do Povo Kalapalo'),
            i::__('Cultura do Povo Kanamari'),
            i::__('Cultura do Povo Karajá'),
            i::__('Cultura do Povo Karipuna'),
            i::__('Cultura do Povo Kaxinawá (Huni Kuin)'),
            i::__('Cultura do Povo Kayabi'),
            i::__('Cultura do Povo Kayapó'),
            i::__('Cultura do Povo Korubo'),
            i::__('Cultura do Povo Krahô'),
            i::__('Cultura do Povo Maxakali'),
            i::__('Cultura do Povo Munduruku'),
            i::__('Cultura do Povo Ofaié'),
            i::__('Cultura do Povo Panará'),
            i::__('Cultura do Povo Pankararu'),
            i::__('Cultura do Povo Pareci'),
            i::__('Cultura do Povo Paresí'),
            i::__('Cultura do Povo Pataxó'),
            i::__('Cultura do povo pomerano'),
            i::__('Cultura do Povo Suruí'),
            i::__('Cultura do Povo Tembé'),
            i::__('Cultura do Povo Terena'),
            i::__('Cultura do Povo Tikuna'),
            i::__('Cultura do Povo Timbira'),
            i::__('Cultura do Povo Tukano'),
            i::__('Cultura do Povo Tupi'),
            i::__('Cultura do Povo Wai Wai'),
            i::__('Cultura do Povo Waimiri-Atroari'),
            i::__('Cultura do Povo Xavante'),
            i::__('Cultura do Povo Xerente'),
            i::__('Cultura do Povo Xikrin'),
            i::__('Cultura do Povo Yanomami'),
            i::__('Cultura do Povo Yawalapiti'),
            i::__('Cultura do Povo Yawanawá'),
            i::__('Cultura do Povo Zoró'),
            i::__('Cultura dos andirobeiros'),
            i::__('Cultura dos apanhadores de flores sempre vivas'),
            i::__('Cultura dos benzedeiros'),
            i::__('Cultura dos caatingueiros'),
            i::__('Cultura dos caboclos'),
            i::__('Cultura dos caiçaras'),
            i::__('Cultura dos catadores de mangaba'),
            i::__('Cultura dos cipozeiros'),
            i::__('Cultura dos extrativistas'),
            i::__('Cultura dos extrativistas costeiros e marinhos'),
            i::__('Cultura dos faxinalenses'),
            i::__('Cultura dos geraizeiros'),
            i::__('Cultura dos ilhéus'),
            i::__('Cultura dos morroquianos'),
            i::__('Cultura dos pantaneiros'),
            i::__('Cultura dos pescadores artesanais'),
            i::__('Cultura dos povos ciganos'),
            i::__('Cultura dos povos e comunidades de terreiro/povos e comunidades de matriz africana'),
            i::__('Cultura dos Povos Nômades'),
            i::__('Cultura dos Povos Originários'),
            i::__('Cultura dos raizeiros'),
            i::__('Cultura dos retireiros do Araguaia'),
            i::__('Cultura dos ribeirinhos'),
            i::__('Cultura dos vazanteiros'),
            i::__('Cultura dos veredeiros'),
            i::__('Cultura e Bem Viver'),
            i::__('Cultura e Comunicação'),
            i::__('Cultura e decolonialidade'),
            i::__('Cultura e Desenvolvimento Social'),
            i::__('Cultura e Direitos Humanos'),
            i::__('Cultura e Educação'),
            i::__('Cultura e Esporte'),
            i::__('Cultura e Juventudes'),
            i::__('Cultura e Lazer'),
            i::__('Cultura e Política'),
            i::__('Cultura e Saúde'),
            i::__('Cultura e Território'),
            i::__('Cultura e Turismo'),
            i::__('Cultura Estrangeira (imigrantes)'),
            i::__('Cultura Hip Hop'),
            i::__('Cultura Italiana'),
            i::__('Cultura Japonesa'),
            i::__('Cultura LGBTQIAPN+'),
            i::__('Cultura Negra'),
            i::__('Cultura Urbana'),
            i::__('Cultura, Infância e Adolescência'),
            i::__('Cultura, Meio Ambiente e Sustentabilidade'),
            i::__('Culturas Afrobrasileiras'),
            i::__('Culturas dos Povos Originários'),
            i::__('Culturas Populares'),
            i::__('Culturas Tradicionais'),
            i::__('Culturas Tradicionais e Populares'),
            i::__('Dança'),
            i::__('Dança Afro'),
            i::__('Dança Contemporânea'),
            i::__('Dança de Salão'),
            i::__('Dança do Ventre'),
            i::__('Dança Moderna'),
            i::__('Dança Silvestre'),
            i::__('Danças Clássicas'),
            i::__('Danças Contemporâneas'),
            i::__('Danças Estrangeiras'),
            i::__('Danças Populares'),
            i::__('Danças Urbanas'),
            i::__('Declamação'),
            i::__('Desenho Industrial'),
            i::__('Design'),
            i::__('Design de Interiores'),
            i::__('Design de Jóias'),
            i::__('Design de Moda'),
            i::__('Design e Serviços Criativos'),
            i::__('Design Gráfico'),
            i::__('Design Paisagístico'),
            i::__('Design para a Sociobioeconomia'),
            i::__('Diário'),
            i::__('Direito'),
            i::__('Direito Autoral'),
            i::__('Documentário'),
            i::__('Drama'),
            i::__('Economia Criativa e da Cultura'),
            i::__('Economia, Produção e Áreas Técnicas da Cultura'),
            i::__('Ensaios'),
            i::__('Epístola'),
            i::__('Epopeia'),
            i::__('Escola de Samba'),
            i::__('Escultura (Artes Visuais)'),
            i::__('Escultura (Artesanato)'),
            i::__('Espetáculo de Circo'),
            i::__('Fábula'),
            i::__('Fandango'),
            i::__('Fanfarra'),
            i::__('Festa do Divino'),
            i::__('Festas Populares'),
            i::__('Festejos Juninos'),
            i::__('Ficção'),
            i::__('Filme-ensaio'),
            i::__('Filologia'),
            i::__('Filosofia'),
            i::__('Folia de Reis'),
            i::__('Fomento editorial'),
            i::__('Forró'),
            i::__('Forró (Dança)'),
            i::__('Fotografia'),
            i::__('Frevo'),
            i::__('Frevo (dança)'),
            i::__('Funk'),
            i::__('Fuxico'),
            i::__('Gastronomia'),
            i::__('Geografia Humana'),
            i::__('Gestão criativa'),
            i::__('Gestão Cultural'),
            i::__('Grafite'),
            i::__('Gravura'),
            i::__('Guarânia'),
            i::__('História'),
            i::__('Humanidades'),
            i::__('Imóvel tombado'),
            i::__('Internet Podcasting'),
            i::__('Interseccionalidades'),
            i::__('Intervenção Urbana'),
            i::__('Jazz (Dança)'),
            i::__('Jogos Eletrônicos/Games'),
            i::__('Jongo'),
            i::__('Jornais e outros periódicos'),
            i::__('K-pop Dance'),
            i::__('Lambada'),
            i::__('Lapidação'),
            i::__('Leitura'),
            i::__('Lenda'),
            i::__('Letras e Literatura (Humanidades)'),
            i::__('Lidas Campeiras'),
            i::__('Linguística'),
            i::__('Literatura'),
            i::__('Literatura Infantil'),
            i::__('Livro'),
            i::__('Livro, Leitura e Literatura'),
            i::__('Macramê'),
            i::__('Maracatu'),
            i::__('Maracatu (Dança)'),
            i::__('Marujada'),
            i::__('Mediação de Leitura'),
            i::__('Memórias'),
            i::__('Mídias Interativas'),
            i::__('Mídias Sociais'),
            i::__('Mito'),
            i::__('Moda de Viola'),
            i::__('Mosaico'),
            i::__('Movimento Sound System'),
            i::__('Museologia'),
            i::__('Museu (Patrimônio Material)'),
            i::__('Museu tombado'),
            i::__('Música'),
            i::__('Música de Câmara'),
            i::__('Música de Concerto'),
            i::__('Música Eletrônica'),
            i::__('Música Instrumental'),
            i::__('Música Popular'),
            i::__('Musical'),
            i::__('Novela'),
            i::__('Obra Seriada'),
            i::__('Oktober Fest'),
            i::__('Ópera'),
            i::__('Orquestra Sinfônica'),
            i::__('Ourivesaria'),
            i::__('Outras Danças'),
            i::__('Outras Danças Clássicas'),
            i::__('Outras Danças Modernas'),
            i::__('Outras Danças Populares'),
            i::__('Paisagens Culturais'),
            i::__('Patrimônio Cultural'),
            i::__('Patrimônio Cultural Imaterial'),
            i::__('Patrimônio Cultural Material'),
            i::__('Patrimônio Histórico Edificado'),
            i::__('Performance'),
            i::__('Performance Literária'),
            i::__('Permacultura'),
            i::__('Pesquisa'),
            i::__('Pintura'),
            i::__('Poesia'),
            i::__('Políticas e Gestão Culturais'),
            i::__('Procissão do Fogaréu'),
            i::__('Produção Audiovisual'),
            i::__('Produção Cultural'),
            i::__('Produção de Eventos'),
            i::__('Psicologia'),
            i::__('Punk'),
            i::__('Rádio'),
            i::__('Rádio Comunitária'),
            i::__('Rádio e TV'),
            i::__('Rap'),
            i::__('Rasqueado'),
            i::__('Realidade Virtual'),
            i::__('Reggae'),
            i::__('Reisado'),
            i::__('Renda'),
            i::__('Renda de Bilro'),
            i::__('Repente'),
            i::__('Rima e improviso'),
            i::__('Rock'),
            i::__('Romance'),
            i::__('Romaria do Divino Pai Eterno'),
            i::__('Salsa (Dança)'),
            i::__('Salvaguarda do Patrimônio Cultural Imaterial'),
            i::__('Samba'),
            i::__('Samba (Dança)'),
            i::__('Samba de Roda'),
            i::__('Sapateado'),
            i::__('Sátira'),
            i::__('Sertanejo'),
            i::__('Sítio Arqueológico'),
            i::__('Sítios Históricos e Arqueológicos'),
            i::__('Slam'),
            i::__('Sociologia'),
            i::__('Stand-up Comedy'),
            i::__('Street Jazz'),
            i::__('Tambor de Crioula'),
            i::__('Tango (Dança)'),
            i::__('Teatro'),
            i::__('Teatro de Bonecos'),
            i::__('Teatro de Improviso'),
            i::__('Teatro de Máscaras'),
            i::__('Teatro de Rua'),
            i::__('Teatro de Sombras'),
            i::__('Teatro do Absurdo'),
            i::__('Teatro do Oprimido'),
            i::__('Teatro Experimental'),
            i::__('Teatro Infantil'),
            i::__('Tecelagem'),
            i::__('Tecnobrega'),
            i::__('Televisão'),
            i::__('Teologia'),
            i::__('Tradução e Interpretação'),
            i::__('Tragédia'),
            i::__('Trançagem'),
            i::__('Transversalidades'),
            i::__('Vídeo'),
            i::__('Vídeo Experimental'),
            i::__('Vídeo Performance'),
            i::__('Vídeo por demanda'),
            i::__('Video Teatro'),
            i::__('Videoarte'),
            i::__('Videocast'),
            i::__('Videoclipe'),
            i::__('Videodança'),
            i::__('Webdesign'),
            i::__('Websérie'),
            i::__('Xaxado'),
            i::__('Xilogravura'),
            i::__('Outra'),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Linguagem'),
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Artes Integradas'),
            i::__('Artes Visuais'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Cultura Digital'),
            i::__('Cultura Indígena'),
            i::__('Cultura Tradicional'),
            i::__('Curso ou Oficina'),
            i::__('Dança'),
            i::__('Exposição'),
            i::__('Hip Hop'),
            i::__('Livro e Literatura'),
            i::__('Música Popular'),
            i::__('Música Erudita'),
            i::__('Palestra, Debate ou Encontro'),
            i::__('Rádio'),
            i::__('Teatro'),
            i::__('Outros')
        )
    ),
    4 => array(
        'slug' => 'funcao',
        'description' => i::__('Função'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__('Acrobata'),
            i::__('Aderecista'),
            i::__('Adestrador circense'),
            i::__('Adestrador(a) para Artes Cênicas'),
            i::__('Afinador de Instrumentos Musicais'),
            i::__('Ajudante de Câmera'),
            i::__('Ajudante de Locação'),
            i::__('Ajudante de Objetos'),
            i::__('Ajudante de Produção'),
            i::__('Amestrador(a)'),
            i::__('Animador'),
            i::__('Antipodista'),
            i::__('Aplicador(a) de sign'),
            i::__('Apresentador de Eventos'),
            i::__('Apresentador de Festas Populares'),
            i::__('Apresentador de Programas de Rádio'),
            i::__('Apresentador de Programas de Televisão'),
            i::__('Apresentador/Animador'),
            i::__('Aramista'),
            i::__('Armeiro(a)'),
            i::__('Arqueólogo(a)'),
            i::__('Arquiteto(a) e Urbanista'),
            i::__('Arranjador'),
            i::__('Arte-Finalista'),
            i::__('Artesão com Material Reciclável'),
            i::__('Artesão Confeccionador de Biojóias e Ecojóias'),
            i::__('Artesão Crocheteiro'),
            i::__('Artesão do Couro'),
            i::__('Artesão Modelador'),
            i::__('Artesão Moveleiro (exceto reciclado)'),
            i::__('Artesão Rendeiro'),
            i::__('Artesão Tecelão'),
            i::__('Artesão Trançador'),
            i::__('Artesão Tricoteiro'),
            i::__('Artesão(ã)'),
            i::__('Artista'),
            i::__('Artista Aéreo'),
            i::__('Artista Circense'),
            i::__('Artista de Rua'),
            i::__('Artista Urbano'),
            i::__('Artista Visual'),
            i::__('Assessor de imprensa'),
            i::__('Assessor(a) de Comunicação'),
            i::__('Assistente Administrativo'),
            i::__('Assistente de Arte'),
            i::__('Assistente de Artista Gráfico'),
            i::__('Assistente de Backstage'),
            i::__('Assistente de Camarim'),
            i::__('Assistente de Câmera'),
            i::__('Assistente de Cenotécnica'),
            i::__('Assistente de comunicação'),
            i::__('Assistente de Continuidade'),
            i::__('Assistente de Controller'),
            i::__('Assistente de Criação Artística'),
            i::__('Assistente de direção'),
            i::__('Assistente de Edição'),
            i::__('Assistente de Edição de Som'),
            i::__('Assistente de Eletricista'),
            i::__('Assistente de Figurino'),
            i::__('Assistente de Ilha de Edição'),
            i::__('Assistente de Maquiagem'),
            i::__('Assistente de Maquinaria'),
            i::__('Assistente de Montagem'),
            i::__('Assistente de Objetos'),
            i::__('Assistente de palco'),
            i::__('Assistente de Pós Produção'),
            i::__('Assistente de produção'),
            i::__('Assistente de Produção (Base ou Set'),
            i::__('Assistente de Produção de Arte'),
            i::__('Assistente de Produção de Elenco'),
            i::__('Assistente de Produção de Locação'),
            i::__('Assistente de Produção Musical'),
            i::__('Assistente de Roteiro'),
            i::__('Assistente de Som'),
            i::__('Assistente de Transporte'),
            i::__('Assistente Mixador(a)'),
            i::__('Atendente Artístico-Cultural'),
            i::__('Atirador de Facas'),
            i::__('Ator/Atriz'),
            i::__('Audiodescritor(a)'),
            i::__('Avaliador de Joias'),
            i::__('Baianas do Acarajé'),
            i::__('Bailarino(a)'),
            i::__('Barreira'),
            i::__('Bate-folha a máquina'),
            i::__('Benzedeiro(a)/Rezadeiro(a)'),
            i::__('Bibliotecário'),
            i::__('Bilheteiro(a)'),
            i::__('Bonequeiro(a)'),
            i::__('Bordadeiro(a)'),
            i::__('Brincante'),
            i::__('Cabeleireiro'),
            i::__('Cabeleireiro(a)'),
            i::__('Camareiro(a)'),
            i::__('Cantor'),
            i::__('Capataz(a) - Montador(a)'),
            i::__('Capoeirista'),
            i::__('Caricaturista'),
            i::__('Carnavalesco(a)'),
            i::__('Carpinteiro(a)'),
            i::__('Cartunista'),
            i::__('Cenógrafo(a)'),
            i::__('Cenotécnico (cinema, vídeo, televisão, teatro e espetáculos)'),
            i::__('Ceramista'),
            i::__('Chargista'),
            i::__('Chef/Cozinheiro(a)'),
            i::__('Chefe de Maquinária'),
            i::__('Cinegrafista'),
            i::__('Colecionador'),
            i::__('Colorista'),
            i::__('Colorista Assistente'),
            i::__('Comedor de Espada'),
            i::__('Comedor de Fogo (pirofagista)'),
            i::__('Cômico de Circo'),
            i::__('Compositor'),
            i::__('Comunicador'),
            i::__('Confeccionador de Acordeão'),
            i::__('Confeccionador de Instrumentos de Corda'),
            i::__('Confeccionador de Instrumentos de Percussão'),
            i::__('Confeccionador de Instrumentos de Sopro (madeira)'),
            i::__('Confeccionador de Instrumentos de Sopro (metal)'),
            i::__('Confeccionador de Órgão'),
            i::__('Confeccionador de Piano'),
            i::__('Conservador/Restaurador'),
            i::__('Consultor de Imagem'),
            i::__('Consultor em Legendagem'),
            i::__('Consultor(a) cultural'),
            i::__('Consultor(a) em Audiodescrição'),
            i::__('Consultor(a) em Braille'),
            i::__('Consultor(a) em Libras'),
            i::__('Contador(a) de Estórias/Histórias'),
            i::__('Continuista'),
            i::__('Contorcionista'),
            i::__('Contra-regra'),
            i::__('Contrarregra'),
            i::__('Coolhunter'),
            i::__('Coordenador(a) de Palco'),
            i::__('Coreógrafo'),
            i::__('Cortineiro(a)'),
            i::__('Costureiro(a)'),
            i::__('Cravador/Cravejador de Joias'),
            i::__('Criador(a) de Conteúdos Criativos Digitais'),
            i::__('Curador(a)'),
            i::__('Dançarino de Rua'),
            i::__('Dançarino de Salão'),
            i::__('Dançarino Popular, de Danças Folclóricas, Parafolclóricas, Tradicionais ou de Raiz'),
            i::__('Dançarino(a)'),
            i::__('Decorador de Eventos'),
            i::__('Desenhista'),
            i::__('Desenhista de Croqui'),
            i::__('Desenhista Detalhista'),
            i::__('Desenhista Técnico'),
            i::__('Desenhista Técnico da Indústria Têxtil'),
            i::__('Desenhista Técnico de Embalagens, Maquetes e Leiautes'),
            i::__('Desenhista Técnico de Mobiliário'),
            i::__('Desenvolvedor(a) de Jogos Eletrônicos'),
            i::__('Desenvolvedor(a) de Sistemas Informacionais'),
            i::__('Desenvolvedor(a) de Software'),
            i::__('Design de Montagem'),
            i::__('Designer de Brinquedos'),
            i::__('Designer de Interiores'),
            i::__('Designer de Jóias'),
            i::__('Designer de Moda'),
            i::__('Designer de Som'),
            i::__('Designer de Vitrines (Vitrinista)'),
            i::__('Designer Gráfico'),
            i::__('Designer Paisagístico'),
            i::__('Diagramador(a)'),
            i::__('Digitalizador(a)'),
            i::__('Diretor Artístico'),
            i::__('Diretor de Arte'),
            i::__('Diretor Musical'),
            i::__('Diretor(a) de Palco'),
            i::__('Dj (disc jockey)'),
            i::__('Domador de Animais'),
            i::__('Dramaturgo(a)'),
            i::__('Dublador(a)'),
            i::__('Editor de Partituras'),
            i::__('Editor de Texto e Imagem'),
            i::__('Editor(a)'),
            i::__('Editor(a) de Livros'),
            i::__('Editor(a) de Som'),
            i::__('Editor(a) de TV e Vídeo'),
            i::__('Educador Museal'),
            i::__('Educador Social'),
            i::__('Educador(a) artistico-cultural'),
            i::__('Eletricista'),
            i::__('Eletricista Chefe'),
            i::__('Engenheiro de Som'),
            i::__('Enólogo(a)'),
            i::__('Ensaiador'),
            i::__('Equilibrista'),
            i::__('Escritor'),
            i::__('Escultor'),
            i::__('Estampador'),
            i::__('Facilitador'),
            i::__('Faquir'),
            i::__('Figurinista'),
            i::__('Finalizador'),
            i::__('Foley'),
            i::__('Fotógrafo'),
            i::__('Fotógrafo Lambe-Lambe'),
            i::__('Funâmbulo'),
            i::__('Fundidor (joalheria e ourivesaria)'),
            i::__('Galerista'),
            i::__('Gambista'),
            i::__('Gestor Cultural'),
            i::__('Gestor de Redes Sociais'),
            i::__('Gestor(a) de Inovação'),
            i::__('Globista'),
            i::__('Grafiteiro(a)'),
            i::__('Gravador de Joias'),
            i::__('Gravador, à mão (encadernação)'),
            i::__('Guia de Turismo'),
            i::__('Guia-intérprete de língua de sinais'),
            i::__('Hacker'),
            i::__('Homem-bala'),
            i::__('Icarista'),
            i::__('Iluminador(a)'),
            i::__('Ilustrador(a)'),
            i::__('Instrumentista'),
            i::__('Instrutor(a)'),
            i::__('Intérprete'),
            i::__('Inventor'),
            i::__('Joalheiro (reparações)'),
            i::__('Jornalista'),
            i::__('Laminador de metais preciosos a mão'),
            i::__('Lapidador de Jóias'),
            i::__('Legendista ou Tradutor(a)'),
            i::__('Logger'),
            i::__('Luthier'),
            i::__('Maestro'),
            i::__('Mágico'),
            i::__('Malabarista'),
            i::__('Maquetista'),
            i::__('Maquetista na Marcenaria'),
            i::__('Maquiador(a)'),
            i::__('Maquinista'),
            i::__('Maquinista de Cinema e Vídeo'),
            i::__('Maquinista de Teatro e Espetáculos'),
            i::__('Marcador(a) de Cena'),
            i::__('Marceneiro'),
            i::__('Marcheteiro'),
            i::__('Mediador'),
            i::__('Mestre da cultura afro-brasileira'),
            i::__('Mestre da Cultura Popular'),
            i::__('Mestre da Cultura Tradicional'),
            i::__('Mestre de cultura ayahuasqueira'),
            i::__('Mestre de cultura indígena'),
            i::__('Mestre de Pista'),
            i::__('Mestre Vidreiro'),
            i::__('Mestre(a) de bateria'),
            i::__('Mestre-sala'),
            i::__('Mestres artífices'),
            i::__('Microfonista'),
            i::__('Mímico'),
            i::__('Miniaturista'),
            i::__('Modelador de Madeira'),
            i::__('Modelista de Calçados'),
            i::__('Modelista de Roupas'),
            i::__('Monociclista de circo'),
            i::__('Montador'),
            i::__('Montador de Palco'),
            i::__('Motorista de Audiovisual'),
            i::__('Multiplicador'),
            i::__('Muralista'),
            i::__('Museólogo(a)'),
            i::__('Músico/Musicista'),
            i::__('Oficineiro(a)'),
            i::__('Operador de Central de Rádio'),
            i::__('Operador de Microfone (boom man)'),
            i::__('Operador de Projetor Cinematográfico'),
            i::__('Operador de Som'),
            i::__('Operador de Transmissor de Rádio'),
            i::__('Operador(a) de Áudio de Continuidade (rádio)'),
            i::__('Operador(a) de Câmera'),
            i::__('Operador(a) de Controle Mestre (rádio)'),
            i::__('Operador(a) de Externa'),
            i::__('Operador(a) de Gravação de Rádio'),
            i::__('Operador(a) de Luz'),
            i::__('Palhaço/Clown'),
            i::__('Paneleiro(a)'),
            i::__('Parteira Indígena'),
            i::__('Parteiro(a)'),
            i::__('Passador (a)'),
            i::__('Passista'),
            i::__('Patinador(a)'),
            i::__('Perna de Pau (ou Pernalta)'),
            i::__('Peruqueiro'),
            i::__('Peruqueiro(a)'),
            i::__('Pesquisador(a)'),
            i::__('Pilotista'),
            i::__('Pirofagista'),
            i::__('Poeta'),
            i::__('Poeta de Slam'),
            i::__('Porta-bandeira/Porta-estandarte'),
            i::__('Produtor Audiovisual'),
            i::__('Produtor de Casting'),
            i::__('Produtor Musical'),
            i::__('Produtor(a) Cultural'),
            i::__('Produtor(a) de Casting/Booker'),
            i::__('Produtor(a) Fonográfico'),
            i::__('Professor'),
            i::__('Profissional da crítica'),
            i::__('Programador(a)'),
            i::__('Projecionista'),
            i::__('Projetista de Móveis'),
            i::__('Projetista de Sistemas de Áudio'),
            i::__('Quadrilheiro(a)'),
            i::__('Quadrinista'),
            i::__('Queijista Artesanal'),
            i::__('Rapper'),
            i::__('Redator(a)'),
            i::__('Rendeiro(a)'),
            i::__('Repórter'),
            i::__('Restaurador de Livros e Documentos'),
            i::__('Restaurador(a)'),
            i::__('Revisor(a)'),
            i::__('Ritmista'),
            i::__('Roadie'),
            i::__('Roteirista'),
            i::__('Rumbeira de Circo'),
            i::__('Sacerdote de religiosidade popular'),
            i::__('Saltimbanco'),
            i::__('Sambista'),
            i::__('Sapateiro'),
            i::__('Secretário de Frente'),
            i::__('Secretário(a) Teatral'),
            i::__('Serigrafista'),
            i::__('Sineiro'),
            i::__('Sonoplasta'),
            i::__('Tacacazeiro(a)'),
            i::__('Tanoeiro(a)'),
            i::__('Tatuador'),
            i::__('Tecelão(ã)'),
            i::__('Técnico (a) em biblioteconomia'),
            i::__('Técnico em Masterização de Áudio'),
            i::__('Técnico em Mixagem de Áudio'),
            i::__('Técnico em Operação de Equipamentos de Transmissão/Recepção de Televisão'),
            i::__('Técnico(a) audiovisual'),
            i::__('Técnico(a) Contábil'),
            i::__('Técnico(a) de arquivo'),
            i::__('Técnico(a) de Estúdio'),
            i::__('Técnico(a) de Iluminação'),
            i::__('Técnico(a) de Som'),
            i::__('Técnico(a) de Som Direto'),
            i::__('Técnico(a) de sonorização'),
            i::__('Técnico(a) em Cenografia'),
            i::__('Técnico(a) em Gravação de Áudio'),
            i::__('Técnico(a) em Instalação de Equipamentos de Áudio'),
            i::__('Técnico(a) em Museologia'),
            i::__('Titeriteiro'),
            i::__('Trabalhador de Confecções de Bijuterias e Jóias de Fantasia'),
            i::__('Tradutor(a)'),
            i::__('Tradutor(a) ou Intérprete de Libras'),
            i::__('Transcritor ou Revisor em Braille'),
            i::__('Trapezista'),
            i::__('Trefilador (joalheria e ourivesaria)'),
            i::__('Turismólogo(a)'),
            i::__('Ventríloquo'),
            i::__('Violeiro'),
            i::__('Visagista'),
            i::__('Visual Merchandiser'),
            i::__('VJ'),
            i::__('Web Designer'),
            i::__('Outra'),
        )
    ),
    5 => array(
        'slug' => 'etnia',
        'description' => i::__('Etnia'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__('Aikanã'),
            i::__('Aikewara'),
            i::__('Akuntsu'),
            i::__('Amanayé'),
            i::__('Amondawa'),
            i::__('Anacé'),
            i::__('Anambé'),
            i::__('Aparai'),
            i::__('Apiaká'),
            i::__('Apinayé'),
            i::__('Apurinã'),
            i::__('Aranã'),
            i::__('Arapaso'),
            i::__('Arapium'),
            i::__('Arara'),
            i::__('AraradaVoltaGrandedoXingu'),
            i::__('AraradoRioAmônia'),
            i::__('AraradoRioBranco'),
            i::__('AraraShawãdawa'),
            i::__('Araweté'),
            i::__('Arikapú'),
            i::__('Aruá'),
            i::__('Ashaninka'),
            i::__('AsurinidoTocantins'),
            i::__('AsurinidoXingu'),
            i::__('Atikum'),
            i::__('Avá-Canoeiro'),
            i::__('AwaGuajá'),
            i::__('Aweti'),
            i::__('Bakairi'),
            i::__('Banawá'),
            i::__('Baniwa'),
            i::__('Bará'),
            i::__('Barasana'),
            i::__('Baré'),
            i::__('Baré(Boe)'),
            i::__('Borari'),
            i::__('Bororo'),
            i::__('CanelaApanyekrá'),
            i::__('CanelaMemortumré'),
            i::__('Chiquitano'),
            i::__('Cintalarga'),
            i::__('Coripaco'),
            i::__('Dâw'),
            i::__('Deni'),
            i::__('Desana'),
            i::__('Djeoromitxí'),
            i::__('Dow'),
            i::__('Enawenê-nawê'),
            i::__('Fulni-ô'),
            i::__('GalibiKa\'lina'),
            i::__('Galibi-Marworno'),
            i::__('Gamela'),
            i::__('GaviãoAkrãtikatêjê'),
            i::__('GaviãoKykatejê'),
            i::__('GaviãoParkatêjê'),
            i::__('GaviãoPykopjê'),
            i::__('Guajajara'),
            i::__('Guarani'),
            i::__('Guató'),
            i::__('Hixkaryana'),
            i::__('HuniKuin'),
            i::__('Hupda'),
            i::__('HupdaIkolenIkpengIngarikóIny'),
            i::__('Jamamadi'),
            i::__('Jaraqui'),
            i::__('Jarawara'),
            i::__('Javaé'),
            i::__('Jenipapo-Kanindé'),
            i::__('Jiahui'),
            i::__('Jiripancó'),
            i::__('Juma'),
            i::__('Ka\'apor'),
            i::__('Kadiwéu'),
            i::__('Kaimbé'),
            i::__('Kaingang'),
            i::__('Kaiowá'),
            i::__('Kaixana'),
            i::__('Kakwa'),
            i::__('Kalankó'),
            i::__('Kalapalo'),
            i::__('Kamaiurá'),
            i::__('Kambeba'),
            i::__('Kambiwá'),
            i::__('Kanamari'),
            i::__('Kanoê'),
            i::__('Kantaruré'),
            i::__('Kapinawa'),
            i::__('KarajádoNorte'),
            i::__('KarajáIranxe'),
            i::__('Karapanã'),
            i::__('Karapotó'),
            i::__('KaripunadeRondônia'),
            i::__('KaripunadoAmapá'),
            i::__('Kariri-Xokó'),
            i::__('Karitiana'),
            i::__('Karo'),
            i::__('Kassupá'),
            i::__('Katuenayana'),
            i::__('KatukinadoRioBiá'),
            i::__('KatukinaPano'),
            i::__('Katxuyana'),
            i::__('Kawaiwete(Kaiabi)'),
            i::__('Kaxarari'),
            i::__('Kaxixó'),
            i::__('Kinikinau'),
            i::__('Kiriri'),
            i::__('Kisêdjê'),
            i::__('Kokama'),
            i::__('Koripako'),
            i::__('Korubo'),
            i::__('Kotiria'),
            i::__('Krahô'),
            i::__('Krahô-Kanela'),
            i::__('Krenak'),
            i::__('Krenyê'),
            i::__('Krikatí'),
            i::__('Kubeo'),
            i::__('Kuikuro'),
            i::__('Kujubim'),
            i::__('Kulina'),
            i::__('KulinaPano'),
            i::__('Kuruaya'),
            i::__('Kwazá'),
            i::__('Macuxi'),
            i::__('Makuna'),
            i::__('Makurap'),
            i::__('Manchineri'),
            i::__('Manoki'),
            i::__('Marubo'),
            i::__('Matipu'),
            i::__('Matis'),
            i::__('Matsés'),
            i::__('Maxakali'),
            i::__('Mbya'),
            i::__('MebengôkreKayapó'),
            i::__('Mehinako'),
            i::__('MenkyManoki'),
            i::__('Migueleno'),
            i::__('Miranha'),
            i::__('Mirity-tapuya'),
            i::__('Mukurin'),
            i::__('Munduruku'),
            i::__('Mura'),
            i::__('Nadöb'),
            i::__('Nahukuá'),
            i::__('Nambikwara'),
            i::__('Ñandeva'),
            i::__('Naruvotu'),
            i::__('Nawa'),
            i::__('Nukak'),
            i::__('Nukini'),
            i::__('Ofaié'),
            i::__('OroWin'),
            i::__('Palikur'),
            i::__('Panará'),
            i::__('Pankaiuká'),
            i::__('Pankará'),
            i::__('Pankararé'),
            i::__('Pankararu'),
            i::__('Pankaru'),
            i::__('Parakanã'),
            i::__('Paresí'),
            i::__('Parintintin'),
            i::__('Patamona'),
            i::__('Pataxó'),
            i::__('PataxóHã-Hã-Hãe'),
            i::__('Paumari'),
            i::__('PipipãPira-tapuya'),
            i::__('Pirahã'),
            i::__('Pira-tapuya'),
            i::__('Pitaguary'),
            i::__('Potiguara'),
            i::__('Puruborá'),
            i::__('Puyanawa'),
            i::__('Rikbaktsa'),
            i::__('Sakurabiat'),
            i::__('SateréMawé'),
            i::__('Shanenawa'),
            i::__('Siriano'),
            i::__('SuruiPaiter'),
            i::__('Suruwaha'),
            i::__('Tabajara'),
            i::__('Taiwano'),
            i::__('Tapajó'),
            i::__('Tapayuna'),
            i::__('Tapeba'),
            i::__('Tapirapé'),
            i::__('Tapuia'),
            i::__('Tariana'),
            i::__('Tatuyo'),
            i::__('Taurepang'),
            i::__('Tembé'),
            i::__('Tenharim'),
            i::__('Terena'),
            i::__('Ticuna'),
            i::__('TinguiBotó'),
            i::__('Tiriyó'),
            i::__('Torá'),
            i::__('Tremembé'),
            i::__('Truká'),
            i::__('Trumai'),
            i::__('Tsohom-dyapa'),
            i::__('Tukano'),
            i::__('Tumbalalá'),
            i::__('Tunayana'),
            i::__('Tupari'),
            i::__('Tupinambá'),
            i::__('Tupiniquim'),
            i::__('Turiwara'),
            i::__('Tuxá'),
            i::__('Tuyuka'),
            i::__('Umutina'),
            i::__('Uru-Eu-Wau-Wau'),
            i::__('WaimiriAtroari'),
            i::__('Waiwai'),
            i::__('Wajãpi'),
            i::__('Wajuru'),
            i::__('Wapichana'),
            i::__('Warekena'),
            i::__('Wari\'Wassu'),
            i::__('Wauja'),
            i::__('Wayana'),
            i::__('Witoto'),
            i::__('Xakriabá'),
            i::__('Xavante'),
            i::__('Xerente'),
            i::__('Xetá'),
            i::__('Xikrin(Mebengôkre)'),
            i::__('Xingu'),
            i::__('Xipaya'),
            i::__('Xokleng'),
            i::__('Xokó'),
            i::__('Xukuru'),
            i::__('Xukuru-Kariri'),
            i::__('Yaminawá'),
            i::__('Yanomami'),
            i::__('Yawalapiti'),
            i::__('Yawanawá'),
            i::__('Ye\'kwana'),
            i::__('Yudja'),
            i::__('Yuhupde'),
            i::__('Yuruti'),
            i::__('Zo\'é'),
            i::__('Zoró'),
            i::__('Outra'),
        )
    )
);
