version: '2'
services:
  mapas_tests:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    volumes:
      - ../src:/var/www/src
      - ../scripts:/var/www/scripts
      - ../compose/local/config-tests.php:/var/www/html/protected/application/conf/config.php
      - ../docker-data/tests-assets:/var/www/html/assets
      - ../docker-data/tests-public-files:/var/www/html/files
      - ../docker-data/tests-private-files:/var/www/private-files
      - ../tests:/var/www/tests
    links:
      - db_tests:db
    
    environment:
      - DB_HOST=db_tests
      - DB_NAME=mapas
      - DB_USER=mapas
      - DB_PASS=mapas

    depends_on:
      - db_tests
      
    stdin_open: true
    tty: true
      
  db_tests:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - ../db/db-test.sql:/docker-entrypoint-initdb.d/db.sql
